server:
  allow_cors: false
  http:
    port: 2222
  grpc:
    port: 9092
  limit:
    enabled: false
chains:
  - name: "subnetwork"
    key_name: "cosmos"
    chain_id: "subnetwork-1"
    rpc_endpoint: "http://139.28.36.148:26657/"
    account_prefix: "cosmos"
    sender: "cosmos17x84atj5m7n6e2yll7gawt72galwzynqptluv7"
    key: "surge arrow stock pizza mad toy because patient author popular quiz always palm source aerobic major receive beach flee stem nut original style frown"
    gas_adjustment: 1.2
    gas_price: "0.01grana"
    drop_coin: "100grana"